### ISSUE TITLE
fix physical equations

### ISSUE THREAD

**Issue by jiskattema** [ESiWACE-S1/qsat#1]
Hi @fjansson , can you have a look at how i've implemented the iteration?
It looks like i'm doing some of the constants wrong, as the temperature is completely wrong at the first step already.

**Comment by fjansson** [comment]
I think the equation is wrong, if you mean this line:
https://github.com/ESiWACE-S1/qsat/blob/b49b4fdf93070adab039f0c338a6a909291a6b04/print_qs.f90#L124
```
c = Rv * c_pd / L**2
Heus2010 = qs * (c * T*T + qt) / (c * T*T + qs)
```

I have this: 
```
b = rlv**2 / (rv * cp * TL**2)   # note b = 1/c from above
qs = qsl * (1 + b*qt) / (1 + b*qsl) 
```
The 1+ is different, and also the T**2 placement.

Here's the corresponding place in my Python code:
https://github.com/ESiWACE-S1/qsat/blob/b49b4fdf93070adab039f0c338a6a909291a6b04/python/thermo.py#L158

**Comment by jiskattema** [comment]
sort of fixed in a new commit
